[package]
name = "doip"
version = "0.1.0"
edition = "2021"

[dependencies]
futures.workspace = true
thiserror.workspace = true
tokio = { workspace = true, optional = true, features = ["time"] }
uds_protocol = { path = "../uds_protocol" }

async-trait = "0.1"
bytes = "1"
byteorder = "1"
tokio-util = { version = "0.7.12", optional = true, features = [
    "net",
    "codec",
] }
tracing.workspace = true
tracing-subscriber = "0.3"


[dev-dependencies]
anyhow = "1"
doip = { path = ".", features = ["client", "server"] }


[features]
default = []
codec = ["dep:tokio", "dep:tokio-util"]
client = ["codec"]
server = ["codec"]
