[package]
name = "uds_on_ip"
version = "0.1.0"
edition = "2024"
description = "UDS session management over DoIP transport"
license = "MIT OR Apache-2.0"
repository = "https://github.com/luminartech/[INTERNAL_PROJECT_REDACTED]"
authors = ["Luminar Technologies <support@luminartech.com>"]

[dependencies]
simple_doip = { workspace = true, features = ["client"] }
uds_protocol.workspace = true

async-trait.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "time", "sync"] }
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "net", "time", "sync", "macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true, features = ["fmt"] }
