"""Sphinx configuration for the uds_services documentation set.

The schema lives here. It is a contract with anything that consumes this set through
needs.json and links to these IDs, so a change here is a change to a published interface
rather than to local configuration.

`tools/validate_needs.py` enforces the parts of the schema that sphinx-needs has no
concept of. Keep the two in step: the permitted values below and the constants in that
script describe the same policy.

This set is deliberately close to `uds_session`'s, so that a reader who knows one knows
the other. It diverges in exactly four ways, each recorded at the point of divergence
below: the ID prefix, the `arch` need type, which fields that type requires, and the two
link types that make the architecture a graph.
"""

import os

project = "uds_services"
author = "MicroVision"
copyright = "2026, MicroVision"  # noqa: A001 - Sphinx requires this name
release = "0.0.0"
# sphinx-needs keys needs.json by `version`, and a consumer pins to that key through
# needs_external_needs. Leaving it unset produces an empty key, which makes a committed
# snapshot impossible to pin to. Keep this in step with the crate version.
version = "0.0.0"

extensions = [
    "sphinx_needs",
    "sphinx_hextra",
    # Every diagram in this set is PlantUML, hand-authored or generated by `needflow`.
    # One diagram language rather than two: `sphinx.ext.graphviz` ships with Sphinx and
    # needs no Python dependency, but it cannot draw a sequence diagram and its raster
    # output is not clickable, so it would have to sit alongside this rather than replace
    # any of it.
    "sphinxcontrib.plantuml",
]

# --- diagrams -----------------------------------------------------------------------

# The renderer is a system dependency, not a Python one: `sphinxcontrib-plantuml` shells
# out to this command. Overridable by environment so a CI runner that installs the jar
# somewhere other than the PATH does not need this file edited.
#
# `-config` applies _plantuml/style.puml to every diagram, which is why no diagram in this
# set carries a skinparam block of its own. The path is absolute because the renderer is
# invoked with a working directory this file does not control.
_style = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_plantuml", "style.puml")
plantuml = f"{os.environ.get('PLANTUML', 'plantuml')} -config {_style}"

# `svg_obj` is chosen for two reasons, and neither is cosmetic.
#
# It embeds through an `<object>` element, so the hyperlinks PlantUML writes into each node
# survive. `svg_img` renders identically and swallows every link, which would cost the
# generated diagrams their whole point — see `needs_flow_engine`.
#
# And it emits the SVG alone. Plain `svg` additionally writes a PNG fallback, which
# `needflow` then asks to scale; scaling a raster needs Pillow, and without it the build
# emits a warning — an error here, since warnings are errors. Adding an imaging library to
# a pinned documentation toolchain to produce a fallback no supported browser needs is the
# wrong trade.
plantuml_output_format = "svg_obj"

source_suffix = {
    ".rst": "restructuredtext",
}

exclude_patterns = [
    "_build",
    # Renderer configuration, not a document. Sphinx would otherwise warn that it is not
    # in any toctree, and warnings are errors.
    "_plantuml",
    # Working design documents, not part of the published set. They are not version
    # controlled, they go stale, and rules written for a single work item leak into later
    # ones if they are read as current. Never include them in published output.
    "superpowers",
    # Instructions addressed to the other repositories in the stack, not a description of
    # this crate. It is tracked so it can be carried between repositories, and excluded so
    # it is not published as though it were part of this crate's architecture.
    "stack-architecture-brief.md",
]

html_theme = "sphinx_hextra"

# The published site is HTML only, for the same reason the workflow prunes needs.json:
# that export is consumed as evidence against a committed snapshot, so no
# machine-consumable form may sit at a stable URL rebuilt on every push, where it could be
# pointed at instead. Sphinx otherwise copies every source document to
# `_sources/*.rst.txt` and links it from each page — the same content in another format.
# Pruning needs.json alone does not close that.
html_copy_source = False
html_show_sourcelink = False

# --- sphinx-needs schema ------------------------------------------------------------

needs_types = [
    # DIVERGENCE 1 of 4 from uds_session: this type does not exist there.
    #
    # An architecture element: a component, a seam, or a structural decision. It is not a
    # requirement and carries no integrity level — see `needs_extra_options` below for why
    # that distinction is enforced rather than merely intended.
    #
    # These are authored by hand, like `llr` and unlike `impl`/`test`. During the prototype
    # phase they are the whole set: requirements are authored from the standard, not from
    # the architecture, so `docs/requirements/` is deliberately absent until that step
    # begins. An empty requirements page would invite exactly the backfill that makes a
    # requirement set agree with the code by construction.
    {
        "directive": "arch",
        "title": "Architecture Element",
        "prefix": "ARCH_",
        "color": "#9FB8D0",
        "style": "node",
    },
    {
        "directive": "llr",
        "title": "Low-Level Requirement",
        "prefix": "LLR_",
        "color": "#BFD8D2",
        "style": "node",
    },
    # `impl` and `test` needs are generated from source annotations by the extractor and
    # imported, never hand-authored. They exist as types so the generated links resolve
    # and so traceability tables can be rendered against them.
    {
        "directive": "impl",
        "title": "Implementation",
        "prefix": "IMPL_",
        "color": "#DF744A",
        "style": "node",
    },
    {
        "directive": "test",
        "title": "Test Case",
        "prefix": "TEST_",
        "color": "#DCB239",
        "style": "node",
    },
]

# IDs are allocated, never renumbered, and never reused. They are permanent from the
# moment anything outside this repository first links to one, so auto-generation is
# refused: a generated ID changes when its surrounding content does.
needs_id_required = True
# DIVERGENCE 2 of 4: the prefix is `UDSSVC_`, where uds_session uses `UDSS_`. Every crate
# in the stack needs its own, because needs.json sets are merged through
# needs_external_needs and a collision there is silent.
needs_id_regex = r"^UDSSVC_(ARCH|LLR)_\d{4}$|^UDSSVC_(IMPL|TEST)_[A-Z0-9_]+$"

needs_extra_options = [
    # What is currently substantiated by evidence.
    #
    # DIVERGENCE 3 of 4: mandatory on `llr`, and *forbidden* on `arch`. The pair below
    # means "what evidence stands behind this claim, and what it must reach" — a
    # requirement concept. An architecture element is a structural decision, not a claim
    # with evidence behind it, so a level on one would be a number with nothing under it.
    # tools/validate_needs.py enforces both halves of that rule.
    "integrity_level",
    # What this requirement is expected to reach. The gap between the two is the
    # outstanding work, and is reportable rather than tacit.
    "target_level",
    # Whether this need was transcribed from a standard or derived by us. Applies to
    # `arch` exactly as it does to `llr`: an architecture element either cites the clause
    # that forces it, or states in a `Rationale:` paragraph why we chose it. This crate
    # has the highest derived fraction in the stack, which is precisely why the
    # distinction is a field rather than a habit.
    "origin",
    # Where in that standard it came from: clause, table or figure. Required when `origin`
    # names a standard, and absent when it is `derived`, which has no clause to cite.
    # Enforced by tools/validate_needs.py.
    "source",
]

needs_extra_links = [
    # DIVERGENCE 4 of 4 from uds_session: these two link types do not exist there.
    #
    # They make the architecture a graph rather than a list, which is what lets `needflow`
    # generate a component diagram that cannot drift from the prose around it. Populating
    # them is also a check on the architecture itself: an element with no edge in either
    # direction is either genuinely standalone or under-described, and the diagram makes
    # which one obvious.
    {
        "option": "depends_on",
        "incoming": "depended on by",
        "outgoing": "depends on",
        "style": "#4a7ba7",
    },
    # Containment, used only where it is real. The stages of the dispatch pipeline are
    # part of the pipeline; the seams are not part of anything, and are left without a
    # parent rather than given a synthetic one to tidy the diagram.
    {
        "option": "part_of",
        "incoming": "comprises",
        "outgoing": "part of",
        "style": "#777",
    },
    {
        "option": "implements",
        "incoming": "implemented by",
        "outgoing": "implements",
        "style": "#777",
    },
    {
        "option": "verifies",
        "incoming": "verified by",
        "outgoing": "verifies",
        "style": "#0b0",
    },
]

needs_statuses = [
    {"name": "draft", "description": "Authored, not yet reviewed. IDs may still move."},
    {"name": "review", "description": "Under review."},
    {"name": "approved", "description": "Reviewed and accepted. The ID is now permanent."},
    {"name": "obsolete", "description": "Withdrawn. The ID is retained and never reused."},
]

# PlantUML rather than graphviz, so that a generated diagram's nodes are hyperlinks to
# the elements they stand for. Navigating the architecture by clicking through it is worth
# more than the prose ordering of any one page, and it is the reason the link types above
# are populated at all.
needs_flow_engine = "plantuml"

# Both link types appear in a generated diagram unless a directive narrows it. Structure
# and dependency are different questions and a diagram showing only one of them misleads.
needs_flow_link_types = ["depends_on", "part_of"]

# Emit needs.json so this set can be consumed through needs_external_needs against a
# committed snapshot.
needs_build_json = True
