"""Sphinx configuration for the uds_stack documentation set.

The schema lives here. It is a contract with anything that consumes this set through
needs.json and links to these IDs, so a change here is a change to a published interface
rather than to local configuration.

`tools/validate_needs.py` enforces the parts of the schema that sphinx-needs has no
concept of. Keep the two in step: the permitted values below and the constants in that
script describe the same policy.

This file is the union of the two per-crate configurations it replaces. uds_services'
config described itself as diverging from uds_session's in exactly four ways -- the
`arch` type, the ID prefix, which fields that type requires, and the two link types that
make the architecture a graph. All four are now simply present, and the divergence notes
are gone because there is nothing left to diverge from.
"""

import os

project = "uds_stack"
author = "MicroVision"
copyright = "2026, MicroVision"  # noqa: A001 - Sphinx requires this name

# The one thing a single project forces a decision on. sphinx-needs keys needs.json by
# `version`, and a consumer pins to that key through needs_external_needs. Each per-crate
# set previously used its crate's version, which worked because each set held one crate.
#
# This set holds five crates. They now share one release version, but that is still the
# wrong key: it moves on every release, and a consumer pinning to this key depends on the
# *schema* below -- the need types, the ID scheme, the required fields, the link types --
# not on the release. The documentation set therefore carries its own version, incremented
# only when the schema changes. It is not the stack's release number and must never be
# made to track it.
release = "0.1.0"
version = "0.1.0"

extensions = [
    "sphinx_needs",
    "sphinx_hextra",
    # Every diagram in this set is PlantUML, hand-authored or generated by `needflow`.
    # One diagram language rather than two: `sphinx.ext.graphviz` ships with Sphinx and
    # needs no Python dependency, but it cannot draw a sequence diagram and its raster
    # output is not clickable, so it would have to sit alongside this rather than replace
    # any of it.
    "sphinxcontrib.plantuml",
]

# --- diagrams -----------------------------------------------------------------------

# The renderer is a system dependency, not a Python one: `sphinxcontrib-plantuml` shells
# out to this command. Overridable by environment so a CI runner that installs the jar
# somewhere other than the PATH does not need this file edited.
_style = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_plantuml", "style.puml")
plantuml = f"{os.environ.get('PLANTUML', 'plantuml')} -config {_style}"

# `svg_obj` embeds through an `<object>` element, so the hyperlinks PlantUML writes into
# each node survive. `svg_img` renders identically and swallows every link, which would
# cost the generated diagrams their whole point. And it emits the SVG alone; plain `svg`
# additionally writes a PNG fallback that `needflow` then asks to scale, which needs
# Pillow, and without it the build emits a warning -- an error here.
plantuml_output_format = "svg_obj"

source_suffix = {
    ".rst": "restructuredtext",
}

exclude_patterns = [
    "_build",
    # Renderer configuration, not a document.
    "_plantuml",
    # Superpowers specs and plans. Gitignored as well; excluded here so a local copy
    # cannot be pulled into the published set.
    "superpowers",
    # The crate sources live beside this directory in the workspace. Sphinx would
    # otherwise walk into them looking for documents.
    "../crates",
]

html_theme = "sphinx_hextra"

# The published site is HTML only, for the same reason the workflow prunes needs.json:
# that export is consumed as evidence against a committed snapshot, so no
# machine-consumable form may sit at a stable URL rebuilt on every push. Sphinx otherwise
# copies every source document to `_sources/*.rst.txt` and links it from each page.
html_copy_source = False
html_show_sourcelink = False

# --- sphinx-needs schema ------------------------------------------------------------

needs_types = [
    # An architecture element: a component, a seam, or a structural decision. It is not a
    # requirement and carries no integrity level -- see `needs_extra_options`.
    {
        "directive": "arch",
        "title": "Architecture Element",
        "prefix": "ARCH_",
        "color": "#9FB8D0",
        "style": "node",
    },
    {
        "directive": "llr",
        "title": "Low-Level Requirement",
        "prefix": "LLR_",
        "color": "#BFD8D2",
        "style": "node",
    },
    # `impl` and `test` needs are generated from source annotations by the extractor and
    # imported, never hand-authored. They exist as types so the generated links resolve
    # and so traceability tables can be rendered against them.
    {
        "directive": "impl",
        "title": "Implementation",
        "prefix": "IMPL_",
        "color": "#DF744A",
        "style": "node",
    },
    {
        "directive": "test",
        "title": "Test Case",
        "prefix": "TEST_",
        "color": "#DCB239",
        "style": "node",
    },
]

# IDs are allocated, never renumbered, and never reused. They are permanent from the
# moment anything outside this repository first links to one, so auto-generation is
# refused: a generated ID changes when its surrounding content does.
needs_id_required = True

# One prefix per crate. This mattered when the sets were merged through
# needs_external_needs, where a collision is silent; it still matters, because the prefix
# is what says which crate owns an ID. Only the two prefixes actually in use are
# registered -- a crate that has authored nothing gets its prefix when it authors
# something, not before.
#
# Keep in step with CRATE_PREFIXES in tools/validate_needs.py.
needs_id_regex = r"^(UDSS|UDSSVC)_(ARCH|LLR)_\d{4}$|^(UDSS|UDSSVC)_(IMPL|TEST)_[A-Z0-9_]+$"

needs_extra_options = [
    # What is currently substantiated by evidence. Mandatory on `llr`, and *forbidden* on
    # `arch`: the pair below means "what evidence stands behind this claim, and what it
    # must reach" -- a requirement concept. An architecture element is a structural
    # decision, not a claim with evidence behind it, so a level on one would be a number
    # with nothing under it. tools/validate_needs.py enforces both halves of that rule.
    "integrity_level",
    # What this requirement is expected to reach. The gap between the two is the
    # outstanding work, and is reportable rather than tacit.
    "target_level",
    # Whether this need was transcribed from a standard or derived by us. Applies to
    # `arch` exactly as it does to `llr`.
    "origin",
    # Where in that standard it came from: clause, table or figure. Required when `origin`
    # names a standard, and absent when it is `derived`.
    "source",
]

needs_extra_links = [
    # These make the architecture a graph rather than a list, which is what lets
    # `needflow` generate a component diagram that cannot drift from the prose around it.
    {
        "option": "depends_on",
        "incoming": "depended on by",
        "outgoing": "depends on",
        "style": "#4a7ba7",
    },
    # Containment, used only where it is real. The stages of the dispatch pipeline are
    # part of the pipeline; the seams are not part of anything, and are left without a
    # parent rather than given a synthetic one to tidy the diagram.
    {
        "option": "part_of",
        "incoming": "comprises",
        "outgoing": "part of",
        "style": "#777",
    },
    {
        "option": "implements",
        "incoming": "implemented by",
        "outgoing": "implements",
        "style": "#777",
    },
    {
        "option": "verifies",
        "incoming": "verified by",
        "outgoing": "verifies",
        "style": "#0b0",
    },
]

needs_statuses = [
    {"name": "draft", "description": "Authored, not yet reviewed. IDs may still move."},
    {"name": "review", "description": "Under review."},
    {"name": "approved", "description": "Reviewed and accepted. The ID is now permanent."},
    {"name": "obsolete", "description": "Withdrawn. The ID is retained and never reused."},
]

# PlantUML rather than graphviz, so that a generated diagram's nodes are hyperlinks to the
# elements they stand for.
needs_flow_engine = "plantuml"

# Both link types appear in a generated diagram unless a directive narrows it. Structure
# and dependency are different questions and a diagram showing only one of them misleads.
needs_flow_link_types = ["depends_on", "part_of"]

# Emit needs.json so this set can be consumed through needs_external_needs against a
# committed snapshot.
needs_build_json = True
